services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bibliotech_db
    ports:
      - "5438:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data