spring:
  application:
    name: bibliotech-api

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/bibliotech_db
    username: postgres
    password: root

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 500MB

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail.smtp.starttls.required: true

file:
  upload_dir: E:/Projetos-SpringBoot/ihc/bibliotech-backend/src/main/java/com/br/bibliotech/Uploads

email:
  subject: "Default Subject"
  message: "Default Message"

jwt:
    secret: 6f7e10b1a3469c7d8e9f123456789abcdef0123456789abcdef0123456789abcd  
    expiration: 3600000 # 1h em milissegundos
