# ========================
# Nome da aplicação
# ========================
spring:
  application:
    name: bibliotech-api

  # ========================
  # Configuração adicional via .env (opcional)
  # ========================
  config:
    import: optional:file:.env[.properties]

  # ========================
  # Configuração do banco de dados (PostgreSQL)
  # ========================
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/bibliotech_db
    username: postgres
    password: root

  # ========================
  # Configurações para upload de arquivos (Multipart)
  # ========================
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 500MB

  # ========================
  # Configuração do JPA / Hibernate
  # ========================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true

# ========================
# Diretório para uploads (imagens/PDFs)
# ========================
file:
  upload-dir: E:/Projetos-Spring/bibliotech-backend/src/main/java/com/br/bibliotech/Uploads

# ========================
# Configuração do servidor (porta)
# ========================
server:
  port: 8080